=== JLLeitschuh/SimpleCMS/SimpleCMS/src/test/resources/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="site">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="section" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="section">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="content" maxOccurs="unbounded" minOccurs="0"/>
                <xs:element ref="children" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="name">
                <xs:simpleType>
                    <xs:restriction base="xs:string"/>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="published">
                <xs:simpleType>
                    <xs:restriction base="xs:boolean" />
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="content">
      <xs:complexType>
          <xs:sequence>
              <xs:element name="body">
                  <xs:simpleType>
                      <xs:restriction base="xs:string"/>
                  </xs:simpleType>
              </xs:element>
          </xs:sequence>
      </xs:complexType>
    </xs:element>
    <xs:element name="children">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="section" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== JLLeitschuh/SimpleCMS/SimpleCMS/src/main/resources/database.xml
<?xml version="1.0" encoding="UTF-8"?>

<site xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="schema.xsd">
    <section id="0" name="menu1" published="true">
        <content>
            <body>its menu1 body</body>
        </content>
        <children>
            <section id="1" name="section11" published="true">
                <content>
                    <body>its body of section 1.1!</body>
                </content>
            </section>
            <section id="2" name="section12" published="true">
                <content>
                    <body>its body of section 1.2!</body>
                </content>
                <children>
                    <section id="3" name="section121" published="true">
                        <content>
                            <body>its last body!</body>
                        </content>                       
                    </section>
                </children>
            </section>
            <section id="4" name="section13" published="false">
                <content>
                    <body>its body of section 1.3!</body>
                </content>
            </section>
        </children>
    </section>
    <section id="5" name="menu2" published="true">
        <content>
            <body>its menu2 body</body>
        </content>
        <children>
            <section id="6" name="section21" published="true">
                <content>
                    <body>its body of section 2.1!</body>
                </content>
            </section>
            <section id="7" name="section22" published="true">
                <content>
                    <body>its body of section 2.2!</body>
                </content>
            </section>
        </children>
    </section>

</site>
